-- Scenario 1: Automatically update the last modified date when a customer's record is updated.
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE
ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

-- Test
UPDATE Customers
SET Balance = Balance + 500
WHERE CustomerID = 1;

COMMIT;

-- Varify
SELECT CustomerID,
       Name,
       Balance,
       LastModified
FROM Customers
WHERE CustomerID = 1;

--------------------------------------------------------------------------------

-- Scenario 2: Maintain an audit log for all transactions.
CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID NUMBER,
    TransactionType VARCHAR2(20),
    Amount NUMBER(10,2),
    TransactionDate DATE,
    AuditDate DATE
);

-- Trigger
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (
        TransactionID,
        AccountID,
        TransactionType,
        Amount,
        TransactionDate,
        AuditDate
    )
    VALUES (
        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.TransactionType,
        :NEW.Amount,
        :NEW.TransactionDate,
        SYSDATE
    );
END;
/

-- Test
INSERT INTO Transactions (
    TransactionID,
    AccountID,
    TransactionType,
    Amount,
    TransactionDate
)
VALUES (
    1006,
    101,
    'Deposit',
    5000,
    SYSDATE
);

COMMIT;

-- Varify
SELECT *
FROM AuditLog;

--------------------------------------------------------------------------------

-- Scenario 3: Enforce business rules on deposits and withdrawals.
CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT
ON Transactions
FOR EACH ROW
DECLARE
    v_balance Accounts.Balance%TYPE;
BEGIN
    -- Check deposit amount
    IF UPPER(:NEW.TransactionType) = 'DEPOSIT' THEN
        IF :NEW.Amount <= 0 THEN
            RAISE_APPLICATION_ERROR(
                -20001,
                'Deposit amount must be greater than zero.'
            );
        END IF;
    END IF;

    -- Check withdrawal balance
    IF UPPER(:NEW.TransactionType) = 'WITHDRAWAL' THEN
        SELECT Balance
        INTO v_balance
        FROM Accounts
        WHERE AccountID = :NEW.AccountID;

        IF :NEW.Amount > v_balance THEN
            RAISE_APPLICATION_ERROR(
                -20002,
                'Insufficient balance for withdrawal.'
            );
        END IF;
    END IF;
END;
/

-- Test Valid Deposit
INSERT INTO Transactions (
    TransactionID,
    AccountID,
    TransactionType,
    Amount,
    TransactionDate
)
VALUES (
    2001,
    101,
    'Deposit',
    5000,
    SYSDATE
);

COMMIT;

-- Test Invalid Deposit
INSERT INTO Transactions (
    TransactionID,
    AccountID,
    TransactionType,
    Amount,
    TransactionDate
)
VALUES (
    2002,
    101,
    'Deposit',
    -500, -- show error, because deposit amount must be greater than zero
    SYSDATE
);


-- Test Invalid Withdrawal
INSERT INTO Transactions (
    TransactionID,
    AccountID,
    TransactionType,
    Amount,
    TransactionDate
)
VALUES (
    2003,
    101,
    'Withdrawal', 
    1000000, -- Insufficient balance for withdrawal
    SYSDATE
);


-- Test Valid Withdrawal

INSERT INTO Transactions (
    TransactionID,
    AccountID,
    TransactionType,
    Amount,
    TransactionDate
)
VALUES (
    2005,
    101,
    'Withdrawal',
    1000,
    SYSDATE
);

COMMIT;