spring.application.name=springlearn
server.port=8083

logging.level.org.springframework=info
logging.level.com.cognizant.springlearn=debug

logging.pattern.console=%d{yyMMdd}|%d{HH:mm:ss.SSS}|%-20.20thread|%-5level|%logger{36}|%M|%msg%n